### ISSUE TITLE
Great add on! Is it customizable?

### ISSUE THREAD

**Issue by deadmaze** [bastianlstrube/ContextPie#10]
Hi @bastianlstrube ! THanks for working on a great add on. I'm debating between this one and passivestar's context menu, although I was curious if there is any way to customize your pie menu buttons? Thanks in advance for your time!

**Comment by bastianlstrube** [comment]
Thank you. 
You can customize the shortcuts, but not choose new functions for menu entries. 
You can fork this repo and map out other functionality if you wish. It isn't too difficult ;)
An editor isn't on my radar at the moment

Seems like passivestar's addon adds a lot of new functionality. My goal was really mostly to map as many of blender's native functions to as few hotkeys as possible with pie menus.

I encourage you to try it out, potentially use both.
Context pie is easily installed from the extensions platform within blender: https://extensions.blender.org/add-ons/contextpie/
