### ISSUE TITLE
Option to change shortcut key

### ISSUE THREAD

**Issue by slrgt** [bastianlstrube/ContextPie#6]
Hi, I just discovered this amazing addon and I was wondering if it would be possible for an update that allows us to set a custom shortcut key. I would like to use Tab instead of Right Click for the pie menu to appear :)

**Comment by bastianlstrube** [comment]
Hello!
Thank you for the feedback. Someone else mentioned they missed this as well in their review on the extension site. I will definitely try to implement it if i can figure out how to do settings in the extension dropdown menus.

Meanwhile, easiest way is to go to edit>preferences>keymap and search for "context pie", "mode selection pie", and "pivots pie" and change the hotkeys that show up individually. Then save your preferences.

**Comment by bastianlstrube** [comment]
Whoops, closed accidentally

**Comment by BastianWombo** [comment]
This feature is now in the new version up on extensions.blender.org!

Thanks again for the feedback
