### ISSUE TITLE
Selecting any option under Snap (pivots pie) turns on proportional editing.

### ISSUE THREAD

**Issue by manavnayyar** [bastianlstrube/ContextPie#9]
I did read that you had to work on Snap Menu from scratch (as per your update on Sep 3). Yet the Snapping Pie menu is working fine except for the small clash with accidentally turning on proportional editing. I hope you will able to fix it soon. 

Also, you are an amazing person and I genuinely appreciate your efforts for creating this addon. It's made everything so much faster.

**Comment by BastianWombo** [comment]
Hi

Thank you so much for commenting. This is only an issue in Object mode yes?
It was an error from copying over another pie menu. It is an easy fix and I'll include it in the next update. It'll be within the next week or two. Got some other changes in the pipeline (:
Meanwhile you can download the zip from here on github, off of the Main branch and it will be fixed.

regarding the missing snap menu... I think I mean the "other" snap... blender also refers to moving "selection to ..." or "Cursor to ..." as Snap... which is hella confusing. Attached a screenshot of the menu. That one also belongs in pivots pie.

Thank you so much. I've been making the tool for myself. I'm grateful blender has made it so easy to contribute extensions to a common repository and happy knowing it benefits others.
